"""add_auth_and_audit_tables

Revision ID: 35e9adbe883f
Revises: d8f13722a89d
Create Date: 2026-08-17 15:45:39.809485

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e9adbe883f'
down_revision: Union[str, Sequence[str], None] = 'd8f13722a89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('operation_detail', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    role_rows = sa.table(
        'roles',
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
        sa.column('created_at', sa.DateTime),
    )
    op.bulk_insert(
        role_rows,
        [
            {
                'code': 'owner',
                'name': 'Owner',
                'description': 'Full account, system, backup, and document administration access.',
                'created_at': datetime.utcnow(),
            },
            {
                'code': 'warehouse_operator',
                'name': 'Warehouse operator',
                'description': 'Stock-in, stock-out, and inventory counting access.',
                'created_at': datetime.utcnow(),
            },
            {
                'code': 'sales_clerk',
                'name': 'Sales clerk',
                'description': 'Sales order creation and payment collection access.',
                'created_at': datetime.utcnow(),
            },
        ],
    )
    op.execute(
        "INSERT INTO system_configs (key, value, description, updated_at) "
        "SELECT 'standalone_mode', 'true', 'Enables legacy local use without a login.', CURRENT_TIMESTAMP "
        "WHERE NOT EXISTS (SELECT 1 FROM system_configs WHERE key = 'standalone_mode')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade is deliberately blocked because it would delete access records."""
    raise RuntimeError("Downgrade is blocked: the access-control migration is forward-only")
