"""initial schema

Revision ID: d8f13722a89d
Revises:
Create Date: 2026-08-17 15:16:21.174741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f13722a89d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='对话内容'),
    sa.Column('business_context', sa.Text(), nullable=True, comment='上下文信息JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chat_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chat_history_session_id'), ['session_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称：粮油/调味/饮料/零食/礼盒/节日品'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='客户名称'),
    sa.Column('customer_type', sa.String(length=50), nullable=True, comment='客户类型：散户/小店/工厂/食堂/VIP'),
    sa.Column('is_vip', sa.Boolean(), nullable=True, comment='是否核心大客户（晨升膳食）'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='电话'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('credit_limit', sa.Float(), nullable=True, comment='欠款额度'),
    sa.Column('current_debt', sa.Float(), nullable=True, comment='当前欠款'),
    sa.Column('total_consumption', sa.Float(), nullable=True, comment='累计消费金额'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('external_market_sync_locks',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('external_market_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quotes_created', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_market_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_market_sync_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_market_sync_runs_status'), ['status'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商/厂家名称'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='电话'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('payment_term', sa.String(length=100), nullable=True, comment='账期说明'),
    sa.Column('cooperation_status', sa.String(length=50), nullable=True, comment='合作状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False, comment='周开始日期'),
    sa.Column('week_end', sa.Date(), nullable=False, comment='周结束日期'),
    sa.Column('total_sales', sa.Float(), nullable=True, comment='本周销售额'),
    sa.Column('total_profit', sa.Float(), nullable=True, comment='本周利润'),
    sa.Column('order_count', sa.Integer(), nullable=True, comment='订单数'),
    sa.Column('hot_products', sa.Text(), nullable=True, comment='热销商品JSON'),
    sa.Column('slow_products', sa.Text(), nullable=True, comment='滞销商品JSON'),
    sa.Column('profitable_products', sa.Text(), nullable=True, comment='高利润商品JSON'),
    sa.Column('low_profit_products', sa.Text(), nullable=True, comment='低利润/走量商品JSON'),
    sa.Column('stock_value', sa.Float(), nullable=True, comment='库存总价值'),
    sa.Column('overstock_risk', sa.Text(), nullable=True, comment='库存积压风险JSON'),
    sa.Column('expired_warning', sa.Text(), nullable=True, comment='临期预警JSON'),
    sa.Column('customer_debts', sa.Text(), nullable=True, comment='客户欠款分析JSON'),
    sa.Column('top_customers', sa.Text(), nullable=True, comment='优质客户JSON'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='下周备货建议、避坑建议、调价建议'),
    sa.Column('ai_business_advice', sa.Text(), nullable=True, comment='商业思维周报内容'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_reports_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='商品编码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品名称'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('spec', sa.String(length=100), nullable=True, comment='规格'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='商品图片'),
    sa.Column('retail_price', sa.Float(), nullable=True, comment='零售价'),
    sa.Column('wholesale_price', sa.Float(), nullable=True, comment='普通批发价'),
    sa.Column('vip_price', sa.Float(), nullable=True, comment='大客户价（晨升膳食专属）'),
    sa.Column('purchase_price', sa.Float(), nullable=True, comment='当前参考进价'),
    sa.Column('safe_stock', sa.Integer(), nullable=True, comment='安全库存'),
    sa.Column('stock_alert_days', sa.Integer(), nullable=True, comment='临期预警天数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否在售'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='入库单号'),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False, comment='采购日期'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='入库总金额'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作员'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_order_no'), ['order_no'], unique=True)

    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='销售单号'),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False, comment='销售日期'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='销售总额'),
    sa.Column('discount_amount', sa.Float(), nullable=True, comment='优惠金额'),
    sa.Column('final_amount', sa.Float(), nullable=True, comment='实收金额'),
    sa.Column('payment_type', sa.String(length=20), nullable=True, comment='结算方式：现结/赊账/部分结账'),
    sa.Column('paid_amount', sa.Float(), nullable=True, comment='已付金额'),
    sa.Column('debt_amount', sa.Float(), nullable=True, comment='欠款金额'),
    sa.Column('customer_type_snapshot', sa.String(length=50), nullable=True, comment='下单时客户类型'),
    sa.Column('price_level_used', sa.String(length=20), nullable=True, comment='使用的价格档次'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作员'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：已完成/已退货'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_order_no'), ['order_no'], unique=True)

    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='关联商品（可选）'),
    sa.Column('price_type', sa.String(length=50), nullable=False, comment='行情类型：同行报价/厂家调价/市场涨跌/节日行情/淡季行情'),
    sa.Column('competitor_price', sa.Float(), nullable=True, comment='同行报价'),
    sa.Column('manufacturer_price', sa.Float(), nullable=True, comment='厂家报价'),
    sa.Column('market_trend', sa.String(length=20), nullable=True, comment='市场趋势：上涨/持平/下跌'),
    sa.Column('content', sa.Text(), nullable=True, comment='行情详细记录'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_prices_id'), ['id'], unique=False)

    op.create_table('pricing_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.DateTime(), nullable=False),
    sa.Column('cost_floor', sa.Float(), nullable=True, comment='保本底价'),
    sa.Column('normal_price', sa.Float(), nullable=True, comment='常规批发价'),
    sa.Column('vip_price', sa.Float(), nullable=True, comment='大客户优惠价'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI分析说明'),
    sa.Column('factors', sa.Text(), nullable=True, comment='影响因素JSON：进价/行情/竞品/周转/淡旺季'),
    sa.Column('confirmed', sa.Boolean(), nullable=True, comment='是否人工确认'),
    sa.Column('confirmed_by', sa.String(length=50), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_references_id'), ['id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False, comment='批次号'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='生产日期'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='到期时间'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='入库数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='采购单价'),
    sa.Column('amount', sa.Float(), nullable=False, comment='金额'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_id'), ['id'], unique=False)

    op.create_table('receivable_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False, comment='Signed receivable balance movement'),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_no', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receivable_ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receivable_ledgers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivable_ledgers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivable_ledgers_reference_no'), ['reference_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_receivable_ledgers_sales_order_id'), ['sales_order_id'], unique=False)

    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='销售单价'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='成本价（来自批次）'),
    sa.Column('amount', sa.Float(), nullable=False, comment='小计金额'),
    sa.Column('profit', sa.Float(), nullable=True, comment='利润'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_items_id'), ['id'], unique=False)

    op.create_table('external_market_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('scope_label', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('quote_kind', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quote_key', sa.String(length=64), nullable=False),
    sa.Column('accepted_market_price_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_market_price_id'], ['market_prices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_market_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_market_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_market_quotes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_market_quotes_quote_key'), ['quote_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_market_quotes_status'), ['status'], unique=False)

    op.create_table('product_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_item_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=False, comment='批次号'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='生产日期'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='到期时间'),
    sa.Column('purchase_price', sa.Float(), nullable=False, comment='采购单价'),
    sa.Column('total_quantity', sa.Float(), nullable=False, comment='入库总量'),
    sa.Column('remaining_quantity', sa.Float(), nullable=False, comment='剩余数量（FIFO出库追踪）'),
    sa.Column('is_expired', sa.Boolean(), nullable=True, comment='是否已过期'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_item_id')
    )
    with op.batch_alter_table('product_batches', schema=None) as batch_op:
        batch_op.create_index('ix_batches_product_expiry', ['product_id', 'expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_batches_id'), ['id'], unique=False)

    op.create_table('batch_outbound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('outbound_quantity', sa.Float(), nullable=False, comment='从该批次出库数量'),
    sa.Column('unit_cost', sa.Float(), nullable=False, comment='该批次单位成本'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['sales_item_id'], ['sales_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_outbound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_outbound_id'), ['id'], unique=False)

    op.create_table('return_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='退货单号'),
    sa.Column('return_type', sa.String(length=20), nullable=False, comment='退货类型：客户退货/供应商退货'),
    sa.Column('related_order_no', sa.String(length=50), nullable=True, comment='关联的原单号'),
    sa.Column('partner_id', sa.Integer(), nullable=True, comment='客户ID或供应商ID'),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=True, comment='退款金额'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='退货原因'),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_orders_order_no'), ['order_no'], unique=True)

    op.create_table('stock_takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('take_date', sa.Date(), nullable=False, comment='盘点日期'),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('system_quantity', sa.Float(), nullable=False, comment='系统数量'),
    sa.Column('actual_quantity', sa.Float(), nullable=False, comment='实际盘点数量'),
    sa.Column('diff_quantity', sa.Float(), nullable=False, comment='盘盈盘亏数量（正盈/负亏）'),
    sa.Column('diff_amount', sa.Float(), nullable=True, comment='盘盈盘亏金额'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='差异原因'),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True, comment='是否已确认'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_takes_id'), ['id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('return_order_id', sa.Integer(), nullable=True),
    sa.Column('stock_take_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_take_id'], ['stock_takes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reference_no'), ['reference_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_return_order_id'), ['return_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_sales_order_id'), ['sales_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_stock_take_id'), ['stock_take_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Prevent the initial schema revision from deleting application data."""
    raise RuntimeError("The initial schema migration cannot be downgraded safely")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_stock_take_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_return_order_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reference_no'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reason'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_batch_id'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_takes_id'))

    op.drop_table('stock_takes')
    with op.batch_alter_table('return_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_return_orders_id'))

    op.drop_table('return_orders')
    with op.batch_alter_table('batch_outbound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_outbound_id'))

    op.drop_table('batch_outbound')
    with op.batch_alter_table('product_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_batches_id'))
        batch_op.drop_index('ix_batches_product_expiry')

    op.drop_table('product_batches')
    with op.batch_alter_table('external_market_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_market_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_external_market_quotes_quote_key'))
        batch_op.drop_index(batch_op.f('ix_external_market_quotes_product_id'))
        batch_op.drop_index(batch_op.f('ix_external_market_quotes_id'))

    op.drop_table('external_market_quotes')
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_items_id'))

    op.drop_table('sales_order_items')
    with op.batch_alter_table('receivable_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivable_ledgers_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_receivable_ledgers_reference_no'))
        batch_op.drop_index(batch_op.f('ix_receivable_ledgers_id'))
        batch_op.drop_index(batch_op.f('ix_receivable_ledgers_customer_id'))

    op.drop_table('receivable_ledgers')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('pricing_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_references_id'))

    op.drop_table('pricing_references')
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_prices_id'))

    op.drop_table('market_prices')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_id'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_code'))

    op.drop_table('products')
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reports_id'))

    op.drop_table('weekly_reports')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.drop_index(batch_op.f('ix_system_configs_id'))

    op.drop_table('system_configs')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('external_market_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_market_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_external_market_sync_runs_id'))

    op.drop_table('external_market_sync_runs')
    op.drop_table('external_market_sync_locks')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chat_history_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_chat_history_id'))

    op.drop_table('ai_chat_history')
    # ### end Alembic commands ###
